### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by oneezy** [Zecat/iron-scroll-spy#12]
The example appears to be broken still.

Also, my [JS Fiddle](https://jsfiddle.net/oneeezy/c3ertupe/) example has partially quit working as well (animated scrolling to sections).

Any idea what the problem could be?

**Comment by Zecat** [comment]
duplicate of #11 ;)
For your fiddle try with the v2 and use `iron-auto-scroll-spy` if you want the auto-scrolling feature, by the way, I forgot to update the readme to explain that!

**Comment by oneezy** [comment]
Ahh.., my bad! I'll fiddle around with it
